version: "2"

services:
#  app:
#    build: docker/app/
#    hostname: app
#    volumes:
#      - .:/var/www/html
#    ports:
#      - "80:80"
#    environment:
#      XDEBUG_HOST: ${XDEBUG_HOST}

  php:
    build: ./docker/php
    volumes:
      - .:/var/www/html
    environment:
      XDEBUG_HOST: ${XDEBUG_HOST}

  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
