version: "2"

services:
  app:
    build: docker/app/
    hostname: app
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    environment:
      XDEBUG_CONFIG: "remote_host=10.0.1.101"

#  db:
#      image: mysql:5.6
#      environment:
#          MYSQL_ROOT_PASSWORD: root
#          MYSQL_DATABASE: kate
#      ports:
#        - "3306:3306"
